FROM ubuntu:latest
LABEL authors="lucas"

# Install API dependencies
#SHELL ["apt-get", "update", "-y"]
#SHELL ["apt-get", "install", "-y", "python3", "python3-pip"]
#WORKDIR /app
#COPY . .
#
## Install PostgresSQL database
#SHELL ["apt-get", "install", "-y", "postgresql"]
#
## Launch API server and Database
#CMD ["python3", "app.py"]